apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsgpt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opsgpt
  template:
    metadata:
      labels:
        app: opsgpt
    spec:
      containers:
      - name: opsgpt-container
        image: YOUR_DOCKER_USERNAME/opsgpt:latest # Use your real Docker image name
        ports:
        - containerPort: 8080