apiVersion: v1
kind: Service
metadata:
  name: opsgpt-service
  namespace: default
spec:
  selector:
    app: opsgpt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer